// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imglyluypdmddumpdwqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZ2x5bHV5cGRtZGR1bXBkd3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTIyODYsImV4cCI6MjA3Mzc2ODI4Nn0.SqPpAkZr41GefT88PlojjU0SvlatOQvqhP14H4nMlu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});